#!/usr/bin/env bash

set -e

source scripts/settings.sh

pushcmd="butler push --userversion=$VER"
target="$1"
shift

case "$target" in
  linux)
    $pushcmd out/linux-x86_64/ $game:linux
    ;;
  windows)
    $pushcmd out/windows/ $game:windows
    ;;
  android)
    $pushcmd out/android/ $game:android
    ;;
  html5)
    $pushcmd out/html5/ $game:html5
    ;;
  all)
    scripts/push linux
    scripts/push windows
    scripts/push android
    scripts/push html5
esac
